/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptographer.ui;

import cryptographer.ciphering.Cipher;
import javax.swing.JOptionPane;

/**
 *
 * @author MaSigMa
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeSelection = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mainJP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        activateB = new javax.swing.JButton();
        cipherRB = new javax.swing.JRadioButton();
        decipherRB = new javax.swing.JRadioButton();
        CBCipherSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cryptographer");

        inputTA.setColumns(20);
        inputTA.setRows(5);
        jScrollPane1.setViewportView(inputTA);
        inputTA.getAccessibleContext().setAccessibleName("");

        jLabel2.setText("input");

        outputTA.setColumns(20);
        outputTA.setRows(5);
        jScrollPane2.setViewportView(outputTA);

        jLabel3.setText("output");

        activateB.setText("activate");
        activateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateBActionPerformed(evt);
            }
        });

        modeSelection.add(cipherRB);
        cipherRB.setSelected(true);
        cipherRB.setText("cipher");
        cipherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipherRBActionPerformed(evt);
            }
        });

        modeSelection.add(decipherRB);
        decipherRB.setText("decipher");
        decipherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decipherRBActionPerformed(evt);
            }
        });

        CBCipherSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a cipher...", "Caesar shift" }));
        CBCipherSelect.setToolTipText("Select the desired cipher");
        CBCipherSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCipherSelectActionPerformed(evt);
            }
        });
        CBCipherSelect.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CBCipherSelectPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout mainJPLayout = new javax.swing.GroupLayout(mainJP);
        mainJP.setLayout(mainJPLayout);
        mainJPLayout.setHorizontalGroup(
            mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBCipherSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(107, 107, 107))
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainJPLayout.createSequentialGroup()
                                .addComponent(cipherRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(decipherRB))
                            .addGroup(mainJPLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(activateB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        mainJPLayout.setVerticalGroup(
            mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPLayout.createSequentialGroup()
                                .addComponent(CBCipherSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cipherRB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decipherRB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activateB))))
                    .addGroup(mainJPLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBCipherSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCipherSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCipherSelectActionPerformed

    private void decipherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decipherRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decipherRBActionPerformed

    private void cipherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipherRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cipherRBActionPerformed

    private void activateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateBActionPerformed
        if (CBCipherSelect.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "error: please select the cipher to use");
        } else if (inputTA.getText().isEmpty()) {
            JOptionPane.showMessageDialog(mainJP, "error: input field can't be empty");
        } else {
            Cipher cipher = new Cipher();
            if (CBCipherSelect.getSelectedIndex() == 1) {
                cipher.setKey(1, JOptionPane.showInputDialog("Please input the shift to use: "));
                if (cipherRB.isSelected()) {
                    outputTA.setText(cipher.cipher(inputTA.getText()));
                } else {
                    outputTA.setText(cipher.decipher(inputTA.getText()));
                }
            }
        }

    }//GEN-LAST:event_activateBActionPerformed

    private void CBCipherSelectPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CBCipherSelectPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCipherSelectPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCipherSelect;
    private javax.swing.JButton activateB;
    private javax.swing.JRadioButton cipherRB;
    private javax.swing.JRadioButton decipherRB;
    private javax.swing.JTextArea inputTA;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainJP;
    private javax.swing.ButtonGroup modeSelection;
    private javax.swing.JTextArea outputTA;
    // End of variables declaration//GEN-END:variables
}
